import re

# Source: https://www.emailchaser.com/learn/spam-trigger-words
SPAM_WORDS = [
    "act",
    "risk free",
    "offer",
    "action",
    "apply",
    "buy",
    "guaranteed",
    "click",
    "link",
    "trial",
    "act now",
    "affordable",
    "amazing",
    "apply now",
    "attention",
    "best price",
    "buy now",
    "cancel",
    "cash",
    "cheap",
    "click below",
    "clearance",
    "congratulations",
    "deal",
    "discount",
    "double your income",
    "earn extra cash",
    "easy",
    "exclusive offer",
    "extra income",
    "fast cash",
    "financial freedom",
    "free",
    "guarantee",
    "hidden",
    "incredible",
    "instant",
    "limited time",
    "make money",
    "money back",
    "no credit check",
    "no hidden costs",
    "no obligation",
    "one time",
    "opportunity",
    "please read",
    "prize",
    "profits",
    "promise",
    "sale",
    "save",
    "special",
    "success",
    "urgent",
    "valuable",
    "win",
    "winner",
    "act immediately",
    "all new",
    "attention required",
    "be your own boss",
    "best price guaranteed",
    "big earnings",
    "call now",
    "cash bonus",
    "check or money order",
    "collect",
    "compare",
    "confidential",
    "cost",
    "credit card offers",
    "dear friend",
    "direct marketing",
    "double your cash",
    "easy terms",
    "exclusive deal",
    "extra cash",
    "fast results",
    "financial independence",
    "for free",
    "for instant access",
    "free access",
    "get paid",
    "hidden charges",
    "important information regarding",
    "increase sales",
    "instant cash",
    "join millions",
    "loans",
    "lowest price",
    "make money fast",
    "million dollars",
    "money back guarantee",
    "no catch",
    "no fees",
    "no hidden fees",
    "no questions asked",
    "not spam",
    "once in a lifetime",
    "order now",
    "outstanding values",
    "performance",
    "please help",
    "priority",
    "pure profit",
    "refinance",
    "risk free trial",
    "satisfaction guaranteed",
    "save big money",
    "see for yourself",
    "serious cash",
    "special promotion",
    "stop",
    "take action",
    "the best",
    "unsecured credit",
    "urgent response",
    "want more",
    "act today",
    "all natural",
    "apply online",
    "avoid bankruptcy",
    "best offer",
    "big savings",
    "cash prize",
    "check",
    "collect now",
    "confidentiality",
    "costs",
    "credit card deals",
    "dear beloved",
    "direct email",
    "double your money",
    "easy money",
    "exclusive opportunity",
    "extra income potential",
    "fast and easy",
    "for instant cash",
    "free bonus",
    "get started now",
    "hidden fees",
    "important notification",
    "increase your sales",
    "instant access",
    "join now",
    "lowest prices",
    "make money online",
    "millionaire",
    "no credit",
    "only today",
    "order today",
    "outstanding offer",
    "personal finance",
    "please respond",
    "private",
    "refinancing",
    "risk free offer",
    "save money",
    "see this",
    "serious money",
    "special offers",
    "stop now",
    "take action now",
    "the best deal",
    "unsecured debt",
    "urgent message",
    "want to earn more",
    "additional income",
    "amazing offer",
    "apply today",
    "bad credit",
    "best price online",
    "big discounts",
    "call now for free",
    "cash incentive",
    "check or cash",
    "collect your cash",
    "confidential message",
    "credit card debt",
    "dear customer",
    "direct mail",
    "double your pay",
    "easy approval",
    "exclusive price",
    "extra money",
    "fast and simple",
    "financial security",
    "free consultation",
    "get paid fast",
    "hidden terms",
    "important information inside",
    "increase your profits",
    "instant approval",
    "join today",
    "lowest rate",
    "make quick money",
    "millionaire mindset",
    "no hidden charges",
    "no strings attached",
    "order yours now",
    "outstanding results",
    "personal loans",
    "please help me",
    "private and confidential",
    "refund",
    "risk free purchase",
    "save now",
    "serious offer",
    "special discounts",
    "stop wasting time",
    "take advantage",
    "the best solution",
    "unsecured loan",
    "urgent notice",
    "want to make money",
    "affordable price",
    "amazing opportunity",
    "apply now and save",
    "bankruptcy",
    "best rates",
    "big profits",
    "call toll free",
    "cash now",
    "check it out",
    "collect your prize",
    "confidentiality guaranteed",
    "credit card fraud",
    "direct response",
    "double your savings",
    "easy cash",
    "exclusive access",
    "extra cash flow",
    "fast delivery",
    "financial success",
    "for only",
    "free demo",
    "get paid today",
    "hidden terms and conditions",
    "important notice",
    "increase your revenue",
    "instant money",
    "join us",
    "lowest rates",
    "make serious money",
    "millionaire secrets",
    "money back policy",
    "no deposit",
    "only a few left",
    "order yours today",
    "outstanding service",
    "personalized offers",
    "please respond asap",
    "refund guaranteed",
    "save money now",
    "see how it works",
    "serious buyers only",
    "special invitation",
    "stop wasting money",
    "take control",
    "the best value",
    "unsecured loan offer",
    "urgent response needed",
    "want to earn extra money",
    "affordable rates",
    "amazing results",
    "apply today and get",
    "be your own boss today",
    "best services",
    "big winners",
    "call toll free now",
    "cash prizes",
    "check out now",
    "collect your reward",
    "confidential and secure",
    "credit card scam",
    "dear sir",
    "dear madam",
    "direct sales",
    "double your success",
    "easy earnings",
    "exclusive content",
    "extra income stream",
    "fast service",
    "financial growth",
    "for your eyes only",
    "free download",
    "get rich quick",
    "high returns",
    "important announcement",
    "increase your savings",
    "instant profit",
    "join today and save",
    "lowest interest rates",
    "make thousands",
    "millionaire lifestyle",
    "money back warranty",
    "no down payment",
    "no hidden fees guaranteed",
    "only for you",
    "order your copy now",
    "outstanding value",
    "personalized solutions",
    "please respond immediately",
    "refund policy",
    "save money today",
    "see results fast",
    "serious inquiries only",
    "special limited offer",
    "stop wasting your money",
    "take immediate action",
    "the best investment",
    "unsecured personal loan",
    "urgent reply required",
    "want to make extra money",
    "amazing bargain",
    "apply today and save",
    "bankruptcy help",
    "best selection",
    "big winners only",
    "call us toll free",
    "cash rewards",
    "check this out",
    "collect your winnings",
    "confidential and trusted",
    "credit card theft",
    "dear valued customer",
    "discounted prices",
    "double your sales",
    "easy and fast",
    "exclusive content inside",
    "extra savings",
    "fast and secure",
    "free gift",
    "get rich today",
    "highest returns",
    "important reminder",
    "increase your wealth",
    "instant results",
    "join us now",
    "lowest prices guaranteed",
    "make unlimited money",
    "millionaire mentor",
    "money back assurance",
    "no fees ever",
    "only limited time",
    "order your today",
    "overwhelming success",
    "personalized offers inside",
    "please reply promptly",
    "refundable",
    "save your money",
    "see the benefits",
    "serious opportunity",
    "special offer inside",
    "stop wasting your time",
    "the best solution for you",
    "unsecured business loan",
    "urgent reply needed",
    "want to make quick money",
    "at no cost",
    "apply today and get started",
    "best seller",
    "big discounts today",
    "call us now",
    "cash back",
    "do you need help",
    "can i help you",
    "how can i help",
    "no risk",
    "not a scam",
    "one time only",
    "no hidden costs",
]


def check_spam(text: str) -> list[str]:
    """Check text for spam trigger words. Returns list of found spam words."""
    # Replace dashes with spaces to catch hyphenated spam words
    normalized = text.replace("-", " ")
    found = []
    seen = set()
    for word in SPAM_WORDS:
        if word in seen:
            continue
        pattern = re.compile(rf"\b{re.escape(word)}\b", re.IGNORECASE)
        if pattern.search(normalized):
            found.append(word)
            seen.add(word)
    return found
